numpy basic vector opration, + , -, *, **

numpy properties: dtype, ndim, shape; what happens when assign float to int?

numpy methods: what is the difference between item() and [] methods?; arange(), reshape(), transpose()

array slicing - begin:end:stride, use syntatic suger of dunder methods

array slice is mutable

numpy broadcasting

computation across different dimensions

matrix multiplication

nearest neighbor search 

numpy indexing and conditional indexing

In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a.shape, a.ndim, a.dtype)

(5,) 1 int64


### python list operation v.s. numpy array operation

In [2]:
a, b = [1,2,3], [4,5,6]
print('regular python list operation:')
print(a * 2)
print(a + b)
c, d = np.array([1,2,3]), np.array([4,5,6])
print('numpy vector operation:')
print(c * 2)
print(c + d)
print(c * d)

regular python list operation:
[1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5, 6]
numpy vector operation:
[2 4 6]
[5 7 9]
[ 4 10 18]


### array broadcasting

In [3]:
a = np.arange(5).reshape(1,-1)
print('a =', a)
print(a.shape)
b =  np.arange(5).reshape(5,-1)
print('b is:\n', b)
print(b.shape)
a + b

a = [[0 1 2 3 4]]
(1, 5)
b is:
 [[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

### numpy array slicing

In [4]:
a = np.arange(20).reshape(4, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
print("get the 3rd row:")
print(a[-3, :])
print("\nget [[13,14],[18,19]] from a:")
print(a[2:, 3:])
print("\nanother way to get [[13,14],[18,19]] from a:")
print(a[-2:, -2:])
print("\nget [5,7,9]:")
print(a[1, ::2])

get the 3rd row:
[5 6 7 8 9]

get [[13,14],[18,19]] from a:
[[13 14]
 [18 19]]

another way to get [[13,14],[18,19]] from a:
[[13 14]
 [18 19]]

get [5,7,9]:
[5 7 9]


### slice is a view into the original object, it is mutable!!

In [6]:
a = np.arange(6)
print(a)
b = a[:3]
b[0] = -1
print(a)

[0 1 2 3 4 5]
[-1  1  2  3  4  5]


### To keep the original array element unchanged, make a copy of it before update the new array!

In [7]:
a = np.arange(6)
print(a)
b = a[:3].copy()
b[0] = -1
print(a)

[0 1 2 3 4 5]
[0 1 2 3 4 5]


### computation across different dimentions:

Suppose we have 4 students taking 3 courses and below shows the grade for each course, students, and semester

dimensions: (semester, student, course)
```
semester1 = [
    [3,4,4],
    [2,3,3],
    [2,2,3],
    [1,2,3]
]
semester2 = [
    [3,3,4],
    [3,3,4],
    [3,3,3],
    [2,3,3]
]
```
calculate average student grade: 
- total average across all students and course and semester
- group by student and course
- group by course
- group by student
- group by student and semester
- group by semester
- group by course and semester

data.mean(axis=?)

In [8]:
semester1 = np.array([
    [3,4,4],
    [2,3,3],
    [2,2,3],
    [1,2,3]
])
semester2 = np.array([
    [3,3,4],
    [3,3,4],
    [3,3,3],
    [2,3,3]
])
all = np.array([semester1, semester2])
print(all.shape)
all

(2, 4, 3)


array([[[3, 4, 4],
        [2, 3, 3],
        [2, 2, 3],
        [1, 2, 3]],

       [[3, 3, 4],
        [3, 3, 4],
        [3, 3, 3],
        [2, 3, 3]]])

In [9]:
print('total average across all students, courses and semesters:')
print(all.mean())
print('\ngroup by student and course')
print(all.mean(axis=(0)))
print('\ngroup by course')
print(all.mean(axis=(0,1)))
print('\ngroup by student')
print(all.mean(axis=(0,2)))
print('\ngroup by student and semester')
print(all.mean(axis=(2)))
print('\ngroup by semester')
print(all.mean(axis=(1,2)))
print('\ngroup by course and semester')
print(all.mean(axis=(1)))

total average across all students, courses and semesters:
2.875

group by student and course
[[3.  3.5 4. ]
 [2.5 3.  3.5]
 [2.5 2.5 3. ]
 [1.5 2.5 3. ]]

group by course
[2.375 2.875 3.375]

group by student
[3.5        3.         2.66666667 2.33333333]

group by student and semester
[[3.66666667 2.66666667 2.33333333 2.        ]
 [3.33333333 3.33333333 3.         2.66666667]]

group by semester
[2.66666667 3.08333333]

group by course and semester
[[2.   2.75 3.25]
 [2.75 3.   3.5 ]]


### matrix multiplication

In [10]:
a = np.arange(3)
print(a)
b = np.arange(3,6)
print(b)
a @ b
# 0 * 3 + 1 * 4 + 2 * 5

[0 1 2]
[3 4 5]


14

### dot product of two arrays

In [11]:
np.dot(a, b)

14

### cross product of a and b in is a vector perpendicular to both a and b

In [12]:
np.cross(a, b)

array([-3,  6, -3])

###  nearest neighbor search 

find the closest point from:
```
[[ 0,  1,  2],
[ 3,  4,  5],
[ 6,  7,  8],
[ 9, 10, 11],
[12, 13, 14],
[15, 16, 17],
[18, 19, 20],
[21, 22, 23],
[24, 25, 26],
[27, 28, 29]]
```
that is closest to `[9,9,9]`


In [13]:
a = np.arange(30).reshape((10, 3))
print('a is:\n', a)
b = np.array([9,9,9])
minIdx = np.argmin(np.linalg.norm(a-b,axis=1))  # compute all euclidean distances at once and return the index of the smallest one
print(f"Nearest point to b is {a[minIdx]}")

a is:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
Nearest point to b is [ 9 10 11]


In [14]:
np.linalg.norm(a-b,axis=1)

array([13.92838828,  8.77496439,  3.74165739,  2.23606798,  7.07106781,
       12.20655562, 17.3781472 , 22.56102835, 27.74887385, 32.93933818])

In [15]:
minIdx

3

###  numpy indexing and conditional indexing

In [16]:
a = np.arange(10)
print(a)
condition = a > 5
print(condition)
# only select the element that is greater than 5
a[condition]

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]


array([6, 7, 8, 9])